// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export async function getRoutes() {
  return {
    routes: {"1":{"exact":true,"path":"/","file":"index","parentId":"@@/global-layout","id":"1"},"2":{"exact":true,"path":"/posts/create","file":"posts/create","parentId":"@@/global-layout","id":"2"},"3":{"exact":true,"path":"/login","file":"login","parentId":"@@/global-layout","id":"3"},"4":{"exact":true,"path":"/posts/:postId","file":"posts/post","parentId":"@@/global-layout","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"/Users/kongshuangshuang/Desktop/demo/umi-blog-example/src/layouts/index.tsx"}},
    routeComponents: {
'1': () => import('../../../src/pages/index'),
'2': () => import('../../../src/pages/posts/create'),
'3': () => import('../../../src/pages/login'),
'4': () => import('../../../src/pages/posts/post'),
'@@/global-layout': () => import('/Users/kongshuangshuang/Desktop/demo/umi-blog-example/src/layouts/index.tsx'),
},
  };
}
